### ISSUE TITLE
iE Driver not open Url

### ISSUE THREAD

**Issue by Regortech** [botcity-dev/botcity-framework-web-python#46]
I am working with a bot using internet explorer.

when i want to open a url i get the following error

to reach a solution;
I change DesiredCapabilities and Options
but not work. 

def default_options(headless=False, download_folder_path=None, user_data_dir=None) -> Options:
  
    ie_options = Options()
    ie_options.add_argument("-embedding")
    ie_options.add_argument("-extoff")
    ie_options.add_argument("-k")
    ie_options.ENSURE_CLEAN_SESSION = True
    ie_options.IGNORE_PROTECTED_MODE_SETTINGS = True
    return ie_options

def default_capabilities() -> Dict:

    desiredCapabilities = DesiredCapabilities.INTERNETEXPLORER
    desiredCapabilities.pop("platform", None)
    desiredCapabilities.pop("version", None)
    desiredCapabilities.pop("ensureCleanSession", True)

    return desiredCapabilities
 

I using Python version 3.9.7 

Traceback (most recent call last):
  File "c:\Users\arzup\Downloads\botcity-framework-web-python-main\examples\rpa-challenge\input-forms\input_bot-vision.py", line 70, in <module>
    Bot.main()
  File "C:\Users\arzup\anaconda3\lib\site-packages\botcity\base\bot.py", line 81, in main
    bot.action(execution)
  File "c:\Users\arzup\Downloads\botcity-framework-web-python-main\examples\rpa-challenge\input-forms\input_bot-vision.py", line 30, in action
    self.navigate_to("https://www.rpachallenge.com/")
  File "C:\Users\arzup\anaconda3\lib\site-packages\botcity\web\bot.py", line 840, in navigate_to
    self.start_browser()
  File "C:\Users\arzup\anaconda3\lib\site-packages\botcity\web\bot.py", line 230, in start_browser
    self._driver = driver_class(options=opt, desired_capabilities=cap, executable_path=driver_path)
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070012 ('There are no more files.') for URL 'http://localhost:50765/'

![Screenshot 2022-03-10 083034](https://user-images.githubusercontent.com/97238858/157595955-0ad4c380-271d-44f6-901c-d3d47cb8b173.png)

**Comment by hhslepicka** [comment]
@Regortech could you provide some more information about your system?

At a minimum it would be good to have:
    * OS Version
    * Python Version
    * IE version


Also, please try this minimal example:
```
from botcity.web import WebBot, Browser


class Bot(WebBot):
    def action(self, execution=None):
        # Set the browser to IE
        self.browser = Browser.IE

        # This assumes that your IE driver is in your path.
        # If not... set the path to it here:
        # self.driver_path = '<PATH_TO_YOUR>\\IEDriverServer.exe'
        
        # Navigate to the website
        self.browse("https://www.botcity.dev")
        self.sleep(5000)
        self.stop_browser()

if __name__ == '__main__':
    Bot.main()
```

**Comment by Regortech** [comment]
OS Version: Windows 11
Python version: 3.9.7
IE Version: 3.14.0

when i tried this code i got error again

**Comment by hhslepicka** [comment]
@Regortech same error as before? I am setting up a Windows VM here to test again.

**Comment by Regortech** [comment]
Traceback (most recent call last):
  File "C:\Users\arzup\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\arzup\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\arzup\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\arzup\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\arzup\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\arzup\anaconda3\lib\runpy.py", line 268, in run_path
  File "C:\Users\arzup\anaconda3\lib\site-packages\botcity\web\bot.py", line 230, in start_browser
    self._driver = driver_class(options=opt, desired_capabilities=cap, executable_path=driver_path)
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\arzup\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070012 ('There are no more files.') for URL 'http://localhost:54317/'

**Comment by hhslepicka** [comment]
@Regortech could you try the points highlighted here: https://botcity-dev.github.io/botcity-framework-web-python/browsers/#important?

**Comment by hhslepicka** [comment]
I was able to run the same quick test that I sent you on my VM.
![image](https://user-images.githubusercontent.com/8185425/157608281-ae1669ce-c465-4bbc-b92f-65cc3e99148e.png)

**Comment by Regortech** [comment]
There is no internet explorer in windows 11. edge opens where i run the program.
![image](https://user-images.githubusercontent.com/97238858/157609800-e21df7d6-9faf-4396-a6bf-5f7d5fcd9c57.png)

**Comment by hhslepicka** [comment]
In this case, use `Edge` as the browser.
Selenium 4 will offer MSEdge with IE support but we still don't support Selenium 4.
The IE option for now is only for `Internet Explorer` as the documentation says.

**Comment by Regortech** [comment]
Thank you
